POST http://localhost:8080/person/
Content-Type: application/json

{
  "name": "stefan",
  "age": 42,
  "role": "ADMIN"
}

###

GET http://localhost:8080/person/dea12055e0136ec337a5e6d23e5a068c7701c9ceb7aeb7bee19b5119f34e95d1
Content-Type: application/json

###

GET http://localhost:8080/person/
Content-Type: application/json